### ISSUE TITLE
Add Volume Setting for Emergency Boost & Fix Ship Thrusters Firing during Emergency Boost

### ISSUE THREAD

**Issue by Hotklou2404** [Owen013/Hikers-Mod#4]
The emergency boost's activation sound is so loud it hurts my ears and annoys me sometimes. I think it should be turned down a little, or if possible a setting could be added that allows me to choose how loud I want it to be.

**Comment by Owen013** [comment]
I added an option to set the emergency boost volume in the config menu. The default emergency boost volume is also slightly lower, because I agree that it's probably too loud.

I just put out a prerelease that should have this feature. Let me know if it works.

Thanks for your feedback!

**Comment by Hotklou2404** [comment]
I like the new volume and the setting to change it, though I think a slider just feels more natural than a value field for the setting.

The pre-release introduces a new issue though - emergency boost now makes a large, blinding explosion on top of me that just feels out of place.

**Comment by Owen013** [comment]
That's weird about the blinding explosion. The jetpack does make a huge flame plume when you do a super-boost, but you should only be able to see that when you look down. And you didn't get the blinding explosion before updating to this prerelease? If possible, could you send a recording of the problem?

Also, the reason I use a number field instead of a slider is that the default volume for the emergency boost sound is 0.75, but the slider moves in increments of 0.10, making it impossible to set the slider to the default volume. I know this isn't ideal, but I haven't found a workaround yet.

**Comment by Hotklou2404** [comment]
I don't get that blinding explosion on the stable release no, only on the pre-release. I'll make a recording later today and get back to you on that.

About the slider; isn't there some way for you to change how much it increments by when it moves? Then you could simply make it move in increments of 0.05 or 0.01.

**Comment by Owen013** [comment]
I guess what I could do is make the slider go from 0 to 2, where 1 would be the default value, 0 would be silent, and 2 would be twice as loud.

I have an idea for what might be causing the bright explosion, but it's kind of a longshot. I hadn't changed anything about the visual effect of the emergency boost in the prerelease, so I'm wondering if the bug is being caused by whether or not the mod was built in debug configuration or release configuration? Debug is the configuration I use while I'm developing, but I usually switch it to release when I publish a new update. I forgot to do that for v1.6.2-pr1, so maybe that's what's causing it? It's hard to tell because it's not happening on my computer.

I know this is a lot, but could you try going to **"C:\Users\[YOUR USERNAME]\AppData\Roaming\OuterWildsModManager\OWML\Mods\Owen013.MovementMod"** and replacing the contents of that folder with that of the zip files below? The first zip file is the mod built in debug configuration, and the second one is the exact same but built in release configuration, so could you test the debug zip file first and then the release one?

Debug Configuration: [Owen013.MovementMod.zip](https://github.com/Owen013/Hikers-Mod/files/13762193/Owen013.MovementMod.zip)
Release Configuration: [Owen013.MovementMod.zip](https://github.com/Owen013/Hikers-Mod/files/13762194/Owen013.MovementMod.zip)

If you can, let me know if you're having the blinding explosion bug in one or both of the configurations.

**Comment by Owen013** [comment]
Also to answer your question about the slider, there currently isn't a good way to change the increment.

**Comment by Hotklou2404** [comment]
If there is no better way to implement the slider (currently at least) then I'd honestly prefer needing to input a numeric value. Then I can fine-tune it much better.

And sorry for not getting back to you sooner like I said I would. Been busy with Christmas-y stuff. I got some time today though! :)

**Comment by Hotklou2404** [comment]
Here's a video of the "flash" I thought I saw: https://streamable.com/ddhaqb (beware I used a free hosting service to share it quickly so there might be ads on the video and the video will be deleted from their servers in 2 days)

It seems it was just one of my ship's thrusters doing a boost as well or something and I was standing too close to it when I tested it before? As you'll see in the video it can indeed be quite blinding if you stand near it, and I'm pretty sure that's not supposed to happen. 

Both of the configurations you gave me cause this to happen, and I tested debug first and then release.

**Comment by Owen013** [comment]
> And sorry for not getting back to you sooner like I said I would. Been busy with Christmas-y stuff. I got some time today though! :)

No worries! Hope you had a good holiday.



> It seems it was just one of my ship's thrusters doing a boost as well or something and I was standing too close to it when I tested it before? As you'll see in the video it can indeed be quite blinding if you stand near it, and I'm pretty sure that's not supposed to happen.

Aha! When I search for the downward thruster at the beginning of the loop, I forgot to add a condition where the downward thruster must be part of the player's jetpack, so the mod must have been saving both the ship's and the player's downward thruster and applying the visual effect to both. A silly mistake on my part, though I'm not sure why it doesn't happen on my computer.

I just put out a new prerelease. Can you let me know if the bug is still happening? Thank you for helping me out with this bugfix, I really appreciate it!

**Comment by Hotklou2404** [comment]
I'm happy to help, it's a pleasure. :)

Also, the thruster is fixed on my end in the newest pre-release! Hurray! :D

**Comment by Owen013** [comment]
Yes! Thanks again for your help!
